web:
  restart: always
  build: ./app
  expose:
    - "5000"
  links:
    - mongodb:mongodb
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn app:application -w 2 -b :5000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

mongodb:
  restart: always
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - mongodb_data:/data/db
